wallpaper {
  monitor = DP-1
  path = /home/seeke/Pictures/jadeos_wallpaper_blue_1920x1080_sharp.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/seeke/Pictures/jadeos_wallpaper_blue_1920x1080_sharp.png
  fit_mode = cover
}

# 予備（monitor空＝fallback）
wallpaper {
  monitor =
  path = /home/seeke/Pictures/jadeos_wallpaper_blue_1920x1080_sharp.png
  fit_mode = cover
}

splash = false
ipc = true
