#
# ~/.tmux.conf :tmux設定ファイル
#

# zshを指定して起動
set-option -g default-shell /bin/zsh

set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:Tc'

# マウス関係
# コピーモードは残しつつ、ホイールで過去ログへ
set -g mouse on
bind -n WheelUpPane if -F "#{mouse_any_flag}" "send-keys -M" "copy-mode -e; send-keys -M"

# 最左に表示
set -g status-left '#H:[#{pane_index}] '

# 分割したら“同じディレクトリ”で開く（超便利）
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# reload
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

# Vimっぽいペイン移動（矢印よりラクな人向け）
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# コピーモードをVi操作に
setw -g mode-keys vi

# ヒストリを１万行に
set -g history-limit 10000
#set -g utf-8 on

# tmuxが端末エミュレータ（Konsoleとか）のウィンドウタイトルを設定する。
set -g set-titles on
# 左：セッション名
set -g status-left '#S '
# セッション名：ウィンドウ番号：ウィンドウ名
set -g set-titles-string "#S:#I:#W"
# 右：日時（要らなければ空に）
set -g status-right '%Y-%m-%d %H:%M '

set -g window-status-format '#I:#W '
set -g window-status-current-format '#[bold]#I:#W#[default] '

# 番号を1始まりに
set -g base-index 1
set -g pane-base-index 1
# ウィンドウを閉じた時に番号を詰め直す（1,2,4が残らない）
set -g renumber-windows on

# tmuxは放っておくと、実行中コマンドとかでウィンドウ名を勝手に変える。
# それを止める設定。
#「自分で rename-window した名前を維持したい」人向け。
setw -g automatic-rename off

