# スクロール設定
scrolling:
  history: 50000
  multiplier: 3
  
#フォント設定  
font:
  size: 10.5
  normal:
    family: 'Mgen+ 1mn'
    style: Regular

  bold:
    family: 'Mgen+ 1mn'
    style: Bold

  italic:
    family: 'Mgen+ 1mn'
    style: Italic

  bold_italic:
    family: 'Mgen+ 1mn'
    style: Bold Italic


#透過設定
window:
    opacity: 0.70

# Colors (Hyper)
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'
  cursor:
    text: '0xF81CE5'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xfe0100'
    green:   '0x33ff00'
    yellow:  '0xfeff00'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x808080'
    red:     '0xfe0100'
    green:   '0x33ff00'
    yellow:  '0xfeff00'
    blue:    '0x0066ff'
    magenta: '0xcc00ff'
    cyan:    '0x00ffff'
    white:   '0xFFFFFF'