set-option -g default-shell /bin/zsh
set-option -g default-terminal screen-256color

set -g mouse on

# #P => ペイン番号
# 最左に表示
set-option -g status-left '#H:[#P]'

# | でペインを縦分割する
bind \ split-window -h
# - でペインを縦分割する
bind - split-window -v


set -g history-limit 10000
#set -g utf-8 on
set -g set-titles on
set -g set-titles-string "#T"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename off
