[mgr]
cwd = { fg = "#a6adc8", bold = true }

hovered         = { reversed = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#f9e2af", bold = true }
find_position = { fg = "#89b4fa", bold = true }

marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked   = { fg = "#89b4fa", bg = "#89b4fa" }
marker_selected = { fg = "#f9e2af", bg = "#f9e2af" }

count_copied   = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut      = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#f9e2af" }

border_symbol = "│"
border_style  = { fg = "#585b70" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#585b70", bg = "#181825" }

progress_label  = { fg = "#cdd6f4", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#313244" }
progress_error  = { fg = "#f38ba8", bg = "#313244" }
