[mgr]
show_hidden = false
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_symlink = true
scrolloff = 5
ratio = [1, 4, 3]

[preview]
tab_size = 4
max_width = 1800
max_height = 1800

[opener]
edit = [
  { run = '${EDITOR:-nvim} "$@"', block = true, desc = "$EDITOR", for = "unix" },
]

open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]

[open]
prepend_rules = [
  { url = "*.txt", use = "edit" },
  { url = "*.md", use = "edit" },
  { url = "*.cpp", use = "edit" },
  { url = "*.c", use = "edit" },
  { url = "*.hpp", use = "edit" },
  { url = "*.h", use = "edit" },
  { url = "*.py", use = "edit" },
  { url = "*.lua", use = "edit" },
  { url = "*.json", use = "edit" },
  { url = "*.toml", use = "edit" },
  { url = "*.yaml", use = "edit" },
  { url = "*.yml", use = "edit" },
  { url = "*.sh", use = "edit" },
  { url = "*.zsh", use = "edit" },
  { url = "*.conf", use = "edit" },
]
